Update cmdline.py
This code change is needed to fix the below issue.
 t = TNEF(open(filename).read(), do_checksum=True) ## filename is winmail.dat
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 1: invalid start byte